### ISSUE TITLE
Apakah support perhitungan dimensi?

### ISSUE THREAD

**Issue by handoyo** [risan/jne#2]
Halo mas, makasih atas library nya. Mau nanya apakah library jne ini dukung perhitungan ongkos kirim berdasarkan volume? Makasih

**Comment by risan** [comment]
@handoyo terimakasih! 

Sayang sekali untuk menghitung ongkos kirim berdasarkan volume barang belum bisa diimplementasikan. 

Package ini mengambil data ongkos kirim dengan cara men-scrape website JNE secara langsung. Jadi selama website JNE: http://www.jne.co.id/home.php tidak menyediakan fasilitas penghitungan berdasarkan volume barang, fitur ini sulit untuk direalisasikan.
